package com.dnee.book.entity;

public enum Genre {
    FANTASY, SCIENCEFICTION, HORROR, ROMANCE, ACTION,
    THRILLER, MYSTERY, DYSTOPIAN, MEMOIR, 
    YOUNGADULT, HISTORICALFICTION, LGBTQ, CONTEMPORARY,
    BIOGRAPHY, LITERARY, SELFHELP, CHILDREN, GRAPHICS, 
    MANGA, MAGICALREALISM
}



